server:
  port: 8082

spring:

  application:
    name: ${SPRING_APPLICATION_NAME:proposal-user-agent-api-local}

keycloak:
  realm: ${KEYCLOAK_REALM:proposal-management}
  client-id: ${KEYCLOAK_CLIENT_ID:proposal-management-client-private}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:v4ctHK7d8Y6HZ6wmcrMuKtmp4ItWOH0m}
  username: ${KEYCLOAK_USERNAME:user-default}
  password: ${KEYCLOAK_PASSWORD:password-default}

external:
  proposal-management-api: ${EXTERNAL_URL_PROPOSAL_MANAGEMENT:http://localhost:8080}
  auth-keycloak-api: ${EXTERNAL_URL_AUTH_KEYCLOAK:http://localhost:9090}